start-at-login = true
# on-focus-changed = ['move-mouse window-lazy-center']
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[mode.main.binding] ###########################################################

    # Windows =================================================================

    alt-cmd-left    = 'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors left'
    alt-cmd-h       = 'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors left'
    alt-cmd-down    = 'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors down'
    alt-cmd-j       = 'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors down'
    alt-cmd-up      = 'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors up'
    alt-cmd-k       = 'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors up'
    alt-cmd-right   = 'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors right'
    alt-cmd-l       = 'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors right'

    alt-cmd-shift-left  = 'move --boundaries all-monitors-outer-frame left'
    alt-cmd-shift-h     = 'move --boundaries all-monitors-outer-frame left'
    alt-cmd-shift-down  = 'move --boundaries all-monitors-outer-frame down'
    alt-cmd-shift-j     = 'move --boundaries all-monitors-outer-frame down'
    alt-cmd-shift-up    = 'move --boundaries all-monitors-outer-frame up'
    alt-cmd-shift-k     = 'move --boundaries all-monitors-outer-frame up'
    alt-cmd-shift-right = 'move --boundaries all-monitors-outer-frame right'
    alt-cmd-shift-l     = 'move --boundaries all-monitors-outer-frame right'

    alt-cmd-comma   = 'layout h_accordion' # 'layout tabbed' in i3
    alt-cmd-period  = 'layout v_accordion' # 'layout stacking' in i3
    alt-cmd-slash   = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

    alt-cmd-f = 'layout floating tiling' # 'floating toggle' in i3

    # Not supported, because this command is redundant in AeroSpace mental model.
    # See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
    #alt-space = 'focus toggle_tiling_floating'

    # `focus parent`/`focus child` are not yet supported, and it's not clear whether they
    # should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
    # alt-a = 'focus parent'

    # Workspaces ==============================================================

    alt-cmd-1 = 'workspace m1'
    alt-cmd-2 = 'workspace m2'
    alt-cmd-3 = 'workspace m3'
    alt-cmd-4 = 'workspace m4'
    alt-cmd-5 = 'workspace m5'
    alt-cmd-6 = 'workspace m6'
    alt-cmd-7 = 'workspace m7'
    alt-cmd-8 = 'workspace m8'
    alt-cmd-9 = 'workspace m9'
    alt-cmd-0 = 'workspace m0'
    alt-cmd-u = 'workspace s1'
    alt-cmd-i = 'workspace s2'
    alt-cmd-o = 'workspace s3'
    alt-cmd-p = 'workspace s4'

    alt-cmd-leftSquareBracket   = 'workspace --wrap-around prev'
    alt-cmd-pageUp              = 'workspace --wrap-around prev'
    alt-cmd-rightSquareBracket  = 'workspace --wrap-around next'
    alt-cmd-pageDown            = 'workspace --wrap-around next'

    alt-cmd-m       = 'focus-monitor --wrap-around next'
    alt-cmd-home    = 'focus-monitor --wrap-around next'

    alt-cmd-shift-1 = 'move-node-to-workspace m1'
    alt-cmd-shift-2 = 'move-node-to-workspace m2'
    alt-cmd-shift-3 = 'move-node-to-workspace m3'
    alt-cmd-shift-4 = 'move-node-to-workspace m4'
    alt-cmd-shift-5 = 'move-node-to-workspace m5'
    alt-cmd-shift-6 = 'move-node-to-workspace m6'
    alt-cmd-shift-7 = 'move-node-to-workspace m7'
    alt-cmd-shift-8 = 'move-node-to-workspace m8'
    alt-cmd-shift-9 = 'move-node-to-workspace m9'
    alt-cmd-shift-0 = 'move-node-to-workspace m0'
    alt-cmd-shift-u = 'move-node-to-workspace s1'
    alt-cmd-shift-i = 'move-node-to-workspace s2'
    alt-cmd-shift-o = 'move-node-to-workspace s3'
    alt-cmd-shift-p = 'move-node-to-workspace s4'

    alt-cmd-shift-leftSquareBracket = ['move-node-to-workspace --wrap-around prev', 'workspace --wrap-around prev']
    alt-cmd-shift-pageUp            = ['move-node-to-workspace --wrap-around prev', 'workspace --wrap-around prev']
    alt-cmd-shift-rightSquareBracket= ['move-node-to-workspace --wrap-around next', 'workspace --wrap-around next']
    alt-cmd-shift-pageDown          = ['move-node-to-workspace --wrap-around next', 'workspace --wrap-around next']

    alt-cmd-shift-m     = ['move-node-to-monitor --wrap-around next', 'focus-monitor --wrap-around next']
    alt-cmd-shift-home  = ['move-node-to-monitor --wrap-around next', 'focus-monitor --wrap-around next']

    # Utils ===================================================================

    # See: https://nikitabobko.github.io/AeroSpace/goodies#open-a-new-window-with-applescript
    alt-cmd-enter = '''exec-and-forget osascript -e '
        tell application "iTerm"
            create window with default profile
            activate
        end tell'
    '''

    alt-cmd-shift-enter = '''exec-and-forget osascript -e '
        tell application "Google Chrome"
            make new window
            activate
        end tell'
    '''

    # Modes ===================================================================

    alt-cmd-a = 'mode alternate'

[mode.alternate.binding] ######################################################

    enter     = 'mode main'
    esc       = 'mode main'
    alt-cmd-a = 'mode main'

    # Windows =================================================================

    alt-cmd-b       = 'balance-sizes'

    alt-cmd-equal   = 'resize smart +50'
    alt-cmd-minus   = 'resize smart -50'

    alt-cmd-left    = 'resize width -50'
    alt-cmd-h       = 'resize width -50'
    alt-cmd-down    = 'resize height +50'
    alt-cmd-j       = 'resize height +50'
    alt-cmd-up      = 'resize height -50'
    alt-cmd-k       = 'resize height -50'
    alt-cmd-right   = 'resize width +50'
    alt-cmd-l       = 'resize width +50'

    alt-cmd-shift-left    = ['join-with left', 'mode main']
    alt-cmd-shift-h       = ['join-with left', 'mode main']
    alt-cmd-shift-down    = ['join-with down', 'mode main']
    alt-cmd-shift-j       = ['join-with down', 'mode main']
    alt-cmd-shift-up      = ['join-with up', 'mode main']
    alt-cmd-shift-k       = ['join-with up', 'mode main']
    alt-cmd-shift-right   = ['join-with right', 'mode main']
    alt-cmd-shift-l       = ['join-with right', 'mode main']

    # Workspaces ==============================================================

    alt-cmd-shift-m     = ['move-workspace-to-monitor --wrap-around next', 'mode main']
    alt-cmd-shift-home  = ['move-workspace-to-monitor --wrap-around next', 'mode main']

    # Utils ===================================================================

    r = ['reload-config', 'mode main']
    z = ['fullscreen', 'mode main']

[workspace-to-monitor-force-assignment] #######################################

    s1 = 'secondary'
    s2 = 'secondary'
    s3 = 'secondary'
    s4 = 'secondary'

